// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRC2tyd8WDGlT1g0mH2HYsDsY1DDNMe4s',
    appId: '1:902554592767:web:5f36f77f878f1b7b1ab3ca',
    messagingSenderId: '902554592767',
    projectId: 'movie-6984b',
    authDomain: 'movie-6984b.firebaseapp.com',
    storageBucket: 'movie-6984b.appspot.com',
    measurementId: 'G-EHMFJBDHDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrgDg62t9swt6gSv_6FmDdP1mB1hGgbt4',
    appId: '1:902554592767:android:b77594dcc1e9257c1ab3ca',
    messagingSenderId: '902554592767',
    projectId: 'movie-6984b',
    storageBucket: 'movie-6984b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxsxZuYE7PhCWairTQPHw-lFLcaL6wJqE',
    appId: '1:902554592767:ios:390a435f89fa4f781ab3ca',
    messagingSenderId: '902554592767',
    projectId: 'movie-6984b',
    storageBucket: 'movie-6984b.appspot.com',
    iosClientId: '902554592767-p6jln02hjdm9aj8ne792frl7dvkm1rbs.apps.googleusercontent.com',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxsxZuYE7PhCWairTQPHw-lFLcaL6wJqE',
    appId: '1:902554592767:ios:93d520874c6eccf21ab3ca',
    messagingSenderId: '902554592767',
    projectId: 'movie-6984b',
    storageBucket: 'movie-6984b.appspot.com',
    iosClientId: '902554592767-ovv8fjld1ncgatej35vt4bvufn9tk0qh.apps.googleusercontent.com',
    iosBundleId: 'com.example.movies.RunnerTests',
  );
}
